-- AlterTable
ALTER TABLE `bowel_movements` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(3),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW(3) ON UPDATE NOW(3);

-- AlterTable
ALTER TABLE `profiles` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(3),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW(3) ON UPDATE NOW(3);

-- AlterTable
ALTER TABLE `user_temps` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(3),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW(3) ON UPDATE NOW(3);

-- AlterTable
ALTER TABLE `users` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
